### ISSUE TITLE
❗ NOTICE OnScheduleFlow: Failing due to missing NodeJs Function index.js

### ISSUE THREAD

**Issue by antoniordz96** [cdklabs/cdk-appflow#16]
**What is the issue?**
The published version available in the NPM Registry does not have `index.js` which is the handler for the `flow-time-updater` function. When deploying `OnScheduleFlow` construct it fails invoking custom resource cause the index.js is missing for the function.

**Error message**

Received response status [FAILED] from custom resource. Message returned: Error: Cannot find module 'index' Require stack: - /var/runtime/index.mjs Logs: /aws/lambda/snow-data-ingestion-ys-de-comamazonawscdkcustomres-D7WRvtHIy6AL Require stack: - /var/runtime/index.mjs at _loadUserApp (file:///var/runtime/index.mjs:1061:17) at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21) at async start (file:///var/runtime/index.mjs:1256:23) at async file:///var/runtime/index.mjs:1262:1 (RequestId: a49ce089-ecea-4032-89c3-06b0af196e96)

**What is the impact?**

Published version is not usable for using `OnScheduleFlow` construct. 

**Workaround**

Forked our own version and using a projen task to copy the index.js to the correct path in the `lib` folder and published in our internal registry

**How do I resolve this?**
Perform the same as workaround or convert the lambda to a typescript lambda and have projen ship http://projen.io/awscdk.html#aws-lambda-functions

**Comment by antoniordz96** [comment]
Had a conversation about with this in cdk.dev https://cdk-dev.slack.com/archives/C01BP9PQHPC/p1692904593706629 to understand if projen could auto put the file in the `lib` folder

**Comment by rpawlaszek** [comment]
Hi @antoniordz96. Thanks for raising this issue. After going through the proposed suggestions I think it will be future-proof to follow [the standard projen approach for AWS CDK](http://projen.io/awscdk.html#aws-lambda-functions). Following this [I restructured the code](https://github.com/cdklabs/cdk-appflow/tree/rpawlasz/fix-missing-flow-updater-lambda/src/core/flows/flow-time-updater). Let me know what you think and if you're okay with the approach.

**Comment by antoniordz96** [comment]
Doing a local build this looks great as I see the `flow-time-updater` lambda generates all the proper files under `lib/core/flow/flow-time=updater`. Much appreciated for this and thanks for the quick turnaround.
